from __future__ import annotations

EVIDENCE_MATCH_THRESHOLD = 0.35
MEDIA_ALLOWED_AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".ogg", ".flac", ".webm"}

MEDIA_ANALYSIS_ROUTE_VERIFY = "VERIFY"
MEDIA_ANALYSIS_ROUTE_SATIRE_EXIT = "SATIRE_EXIT"
MEDIA_ANALYSIS_ROUTE_OUT_OF_SCOPE_EXIT = "OUT_OF_SCOPE_EXIT"

MEDIA_CONTENT_CATEGORY_GOVERNMENT = "government_claim"
MEDIA_CONTENT_CATEGORY_COMMENTARY = "commentary"
MEDIA_CONTENT_CATEGORY_SATIRE = "satire"
MEDIA_CONTENT_CATEGORY_OUT_OF_SCOPE = "out_of_scope"
