export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c9beff",
        "surface-container-high": "#2b2834",
        "primary-container": "#5e2bff",
        tertiary: "#ffb59c",
        "danger-bold": "#FF3366",
        "background-deep": "#080810",
        error: "#ffb4ab",
        "success-neon": "#00F5A0",
        "on-primary-fixed": "#1b0063",
        "tertiary-container": "#aa3700",
        "on-tertiary-fixed": "#380c00",
        "surface-base": "#0D0D0D",
        "surface-bright": "#3a3844",
        "surface-elevated": "#1A1A2E",
        "on-tertiary": "#5c1a00",
        "on-surface": "#e6e0f0",
        primary: "#c9beff",
        "primary-fixed-dim": "#c9beff",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#ffdbce",
        "inverse-on-surface": "#312f3b",
        "on-surface-variant": "#c9c3da",
        "on-tertiary-container": "#ffcebe",
        "surface-container-low": "#1c1a25",
        "inverse-surface": "#e6e0f0",
        "accent-warm": "#F19C79",
        "on-secondary": "#552006",
        "tertiary-fixed-dim": "#ffb59c",
        "primary-fixed": "#e6deff",
        "inverse-primary": "#5e2aff",
        "accent-electric": "#5E2BFF",
        "surface-container-highest": "#36333f",
        "surface-variant": "#36333f",
        "on-background": "#e6e0f0",
        "on-primary-container": "#dcd4ff",
        "on-error": "#690005",
        "error-container": "#93000a",
        "text-primary": "#F0EFF4",
        "outline-variant": "#484457",
        "surface-container-lowest": "#0e0d17",
        "on-secondary-container": "#f6a07d",
        "secondary-fixed-dim": "#ffb598",
        "on-tertiary-fixed-variant": "#822800",
        "secondary-container": "#72351a",
        secondary: "#ffb598",
        "on-secondary-fixed-variant": "#72351a",
        "surface-dim": "#14121d",
        outline: "#938ea3",
        "on-primary": "#2f009b",
        background: "#14121d",
        surface: "#14121d",
        "surface-container": "#201e29",
        "on-secondary-fixed": "#370e00",
        "on-primary-fixed-variant": "#4600d8",
        "tertiary-fixed": "#ffdbcf"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "16px",
        "sidebar-collapsed": "80px",
        "container-padding": "24px",
        unit: "4px",
        "card-gap": "12px",
        "sidebar-width": "260px"
      },
      fontFamily: {
        "hero-display": ["Space Grotesk"],
        "data-num": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "terminal-log": ["JetBrains Mono"],
        "body-base": ["Inter"],
        "badge-label": ["JetBrains Mono"]
      },
      fontSize: {
        "hero-display": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-num": ["18px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "terminal-log": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "badge-label": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }]
      }
    }
  },
  plugins: []
}
