export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#E0E7FF",
        "surface-container-high": "rgba(51, 65, 85, 0.5)",
        "primary-container": "rgba(37, 99, 235, 0.2)",
        tertiary: "#FDE68A",
        "danger-bold": "#EF4444",
        "background-deep": "transparent",
        error: "#FCA5A5",
        "success-neon": "#10B981",
        "on-primary-fixed": "#1E3A8A",
        "tertiary-container": "#FEF3C7",
        "on-tertiary-fixed": "#78350F",
        "surface-base": "rgba(15, 23, 42, 0.7)",
        "surface-bright": "rgba(30, 41, 59, 0.7)",
        "surface-elevated": "rgba(30, 41, 59, 0.8)",
        "on-tertiary": "#92400E",
        "on-surface": "#F8FAFC",
        primary: "#3B82F6",
        "primary-fixed-dim": "#BFDBFE",
        "on-error-container": "#7F1D1D",
        "secondary-fixed": "#FFEDD5",
        "inverse-on-surface": "#0F172A",
        "on-surface-variant": "#94A3B8",
        "on-tertiary-container": "#B45309",
        "surface-container-low": "rgba(15, 23, 42, 0.5)",
        "inverse-surface": "#F8FAFC",
        "accent-warm": "#F59E0B",
        "on-secondary": "#9A3412",
        "tertiary-fixed-dim": "#FDE68A",
        "primary-fixed": "#DBEAFE",
        "inverse-primary": "#93C5FD",
        "accent-electric": "#3B82F6",
        "surface-container-highest": "rgba(71, 85, 105, 0.5)",
        "surface-variant": "rgba(30, 41, 59, 0.5)",
        "on-background": "#F8FAFC",
        "on-primary-container": "#DBEAFE",
        "on-error": "#FFFFFF",
        "error-container": "#7F1D1D",
        "text-primary": "#F8FAFC",
        "outline-variant": "rgba(71, 85, 105, 0.5)",
        "surface-container-lowest": "rgba(2, 6, 23, 0.5)",
        "on-secondary-container": "#FFEDD5",
        "secondary-fixed-dim": "#FED7AA",
        "on-tertiary-fixed-variant": "#92400E",
        "secondary-container": "#9A3412",
        secondary: "#F97316",
        "on-secondary-fixed-variant": "#9A3412",
        "surface-dim": "rgba(15, 23, 42, 0.8)",
        outline: "#475569",
        "on-primary": "#FFFFFF",
        background: "transparent",
        surface: "rgba(15, 23, 42, 0.7)",
        "surface-container": "rgba(30, 41, 59, 0.5)",
        "on-secondary-fixed": "#431407",
        "on-primary-fixed-variant": "#1D4ED8",
        "tertiary-fixed": "#FEF3C7"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        gutter: "16px",
        "sidebar-collapsed": "80px",
        "container-padding": "24px",
        unit: "4px",
        "card-gap": "12px",
        "sidebar-width": "260px"
      },
      fontFamily: {
        "hero-display": ["Space Grotesk"],
        "data-num": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "headline-lg": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "terminal-log": ["JetBrains Mono"],
        "body-base": ["Inter"],
        "badge-label": ["JetBrains Mono"],
        "general-sans": ["General Sans", "sans-serif"],
        "geist-sans": ["Geist Sans", "Inter", "sans-serif"]
      },
      fontSize: {
        "hero-display": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-num": ["18px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "terminal-log": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
        "body-base": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "badge-label": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }]
      },
      animation: {
        marquee: "marquee 20s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        }
      }
    }
  },
  plugins: []
}
